"""The one file the stack cannot start without, and how it comes to exist.

Every service mounts `<runtime>/secrets.env`. Nothing created it and nothing said
what belonged in it, so a correct deployment was impossible from the repository
alone. This generates it with strong random values, refuses to overwrite one that
already exists, and prints nothing sensitive.

    python -m delivery.secrets init /var/lib/nda      # generate
    python -m delivery.secrets check /var/lib/nda     # is it complete?

/var/lib, not /run: this file and everything beside it must survive a reboot,
and /run is a tmpfs on every systemd host.

A secret is generated here only when the platform itself is the sole consumer -
the database and object-store passwords it hands to its own services. Anything an
outside system also knows (a real SMTP password, a production S3 key) must be
supplied, so `init` leaves those blank and `check` reports them as missing.
"""
import argparse
import os
import pathlib
import secrets
import stat

# What each service reads, and whether we can invent it.
# (name, generated?, why it exists)
REQUIRED = [
    ("POSTGRES_PASSWORD", True, "Iceberg catalog and Keycloak share this database"),
    ("KEYCLOAK_ADMIN_PASSWORD", True, "Bootstrap admin for the realm"),
    ("KC_DB_PASSWORD", True, "Keycloak's own connection to Postgres"),
    ("CATALOG_JDBC_PASSWORD", True, "Iceberg REST catalog's connection to Postgres"),
    ("KC_BOOTSTRAP_ADMIN_PASSWORD", True, "What Keycloak 26 itself reads for that admin"),
    ("MSSQL_SA_PASSWORD", True, "SQL Server sa account, source of the CDC stream"),
    ("SQLSERVER_PASSWORD", True, "Simulator's least-privilege SQL Server account"),
    ("DEBEZIUM_PASSWORD", True, "CDC reader's SQL Server account"),
    ("MINIO_ROOT_USER", True, "Object store root identity"),
    ("MINIO_ROOT_PASSWORD", True, "Object store root credential"),
    ("AWS_ACCESS_KEY_ID", True, "What Trino and Flink present to MinIO"),
    ("AWS_SECRET_ACCESS_KEY", True, "Paired with the above"),
    ("NDA_API_KEY", True, "Caller key for the serving API"),
    ("ERASURE_PASSWORD", True, "The only principal permitted to DELETE, for GDPR erasure"),
]

# SQL Server rejects passwords without mixed case, a digit and a symbol, and the
# container exits with a message that does not mention the policy.
COMPLEX = {"MSSQL_SA_PASSWORD"}


# Some of these names are not separate credentials - they are second names for
# one credential, and a different random value in each is a broken stack that
# looks correctly configured. Both instances cost a CI run:
#
#   the Postgres three   Keycloak and the Iceberg catalog connect to the SAME
#                        database as the SAME `nda` user that POSTGRES_PASSWORD
#                        initialises. Three values meant two services that
#                        started and then could not authenticate, reported as
#                        "iceberg-rest is unhealthy" rather than as a password.
#   the Keycloak two     everything here has always called it
#                        KEYCLOAK_ADMIN_PASSWORD; Keycloak 26 itself reads
#                        KC_BOOTSTRAP_ADMIN_PASSWORD. The dev stack bridges them
#                        by shell interpolation, which an env_file cannot do, so
#                        Keycloak saw a username with no password and exited in a
#                        restart loop.
#
# ALIAS is derived-name -> source-name. The source must be generated first.
ALIAS = {
    "KC_DB_PASSWORD": "POSTGRES_PASSWORD",
    "CATALOG_JDBC_PASSWORD": "POSTGRES_PASSWORD",
    "KC_BOOTSTRAP_ADMIN_PASSWORD": "KEYCLOAK_ADMIN_PASSWORD",
    # A fresh single-node MinIO instance only has its root identity. The S3
    # clients therefore must use that same identity until a separate least-
    # privilege MinIO user and policy are provisioned.
    "AWS_ACCESS_KEY_ID": "MINIO_ROOT_USER",
    "AWS_SECRET_ACCESS_KEY": "MINIO_ROOT_PASSWORD",
}


def _value(name, produced=None):
    source = ALIAS.get(name)
    if source:
        if not (produced or {}).get(source):
            raise AssertionError(f"{name} aliases {source}, which REQUIRED lists after it")
        return produced[source]
    token = secrets.token_urlsafe(24)
    return token + "aA1#" if name in COMPLEX else token


def path_for(runtime):
    return pathlib.Path(runtime) / "secrets.env"


def init(runtime, force=False):
    target = path_for(runtime)
    if target.exists() and not force:
        raise SystemExit(
            f"{target} already exists. Refusing to overwrite it - regenerating "
            f"secrets orphans every password already stored in Postgres, MinIO "
            f"and SQL Server.{os.linesep}  Pass --force only on a stack you are "
            f"rebuilding from empty volumes.")
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by `python -m delivery.secrets init`. Never commit this.",
             "# Regenerating it orphans the credentials already stored in the volumes.", ""]
    generated = 0
    produced = {}
    for name, auto, why in REQUIRED:
        lines.append(f"# {why}")
        if auto:
            produced[name] = _value(name, produced)
            lines.append(f"{name}={produced[name]}")
            generated += 1
        else:
            lines.append(f"{name}=")
        lines.append("")
    target.write_text(os.linesep.join(lines), encoding="utf-8")
    # Readable only by the owner. The file holds every credential in the stack.
    try:
        os.chmod(target, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass
    print(f"Wrote {target} with {generated} generated secrets")
    blank = [n for n, auto, _ in REQUIRED if not auto]
    if blank:
        print("  Fill in by hand before deploying: " + ", ".join(blank))
    return target


def check(runtime):
    """Report what is missing without printing any value."""
    target = path_for(runtime)
    if not target.exists():
        print(f"  [FAIL] {target} does not exist")
        print("         python -m delivery.secrets init " + str(runtime))
        return 1
    present = {}
    for line in target.read_text(encoding="utf-8").splitlines():
        if line.strip() and not line.startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            present[key.strip()] = value.strip()
    missing = [n for n, _, _ in REQUIRED if not present.get(n)]
    weak = [n for n, _, _ in REQUIRED if 0 < len(present.get(n, "")) < 16]
    # A hand-edited file can reintroduce the mismatch, and the symptom is never
    # legible: a service that starts and then reports itself unhealthy, or one
    # that restart-loops. So say it here, where the cause is still visible.
    mismatched = [(n, src) for n, src in ALIAS.items()
                  if present.get(n) and present.get(n) != present.get(src)]
    for name, _, why in REQUIRED:
        state = "missing" if name in missing else ("too short" if name in weak else "set")
        print(f"  [{'FAIL' if state != 'set' else 'ok'}] {name:26} {state:10} {why}")
    if mismatched:
        print()
        for name, source in mismatched:
            print(f"  [FAIL] {name} must equal {source} - it is the same credential")
        print("         under a second name. Different values leave the service")
        print("         starting and then failing to authenticate, which is reported")
        print("         as an unhealthy container rather than as a wrong password.")
    print()
    if missing or weak or mismatched:
        print(f"{len(missing) + len(weak) + len(mismatched)} secret(s) need attention in {target}")
        return 1
    print(f"All {len(REQUIRED)} secrets present in {target}")
    return 0


def main():
    parser = argparse.ArgumentParser(description="The stack's secrets.env")
    parser.add_argument("action", choices=["init", "check"])
    parser.add_argument("runtime", nargs="?", default=os.environ.get("NDA_RUNTIME", "/var/lib/nda"))
    parser.add_argument("--force", action="store_true",
                        help="Overwrite an existing secrets.env. Only on empty volumes.")
    args = parser.parse_args()
    if args.action == "init":
        init(args.runtime, args.force)
        return 0
    return check(args.runtime)


if __name__ == "__main__":
    raise SystemExit(main())
