"""The one file the stack cannot start without, and how it comes to exist.

Every service mounts `<runtime>/secrets.env`. Nothing created it and nothing said
what belonged in it, so a correct deployment was impossible from the repository
alone. This generates it with strong random values, refuses to overwrite one that
already exists, and prints nothing sensitive.

    python -m delivery.secrets init /var/lib/nda      # generate
    python -m delivery.secrets check /var/lib/nda     # is it complete?

/var/lib, not /run: this file and everything beside it must survive a reboot,
and /run is a tmpfs on every systemd host.

A secret is generated here only when the platform itself is the sole consumer -
the database and object-store passwords it hands to its own services. Anything an
outside system also knows (a real SMTP password, a production S3 key) must be
supplied, so `init` leaves those blank and `check` reports them as missing.
"""
import argparse
import os
import pathlib
import secrets
import stat

# What each service reads, and whether we can invent it.
# (name, generated?, why it exists)
REQUIRED = [
    ("POSTGRES_PASSWORD", True, "Iceberg catalog and Keycloak share this database"),
    ("KEYCLOAK_ADMIN_PASSWORD", True, "Bootstrap admin for the realm"),
    ("KC_DB_PASSWORD", True, "Keycloak's own connection to Postgres"),
    ("CATALOG_JDBC_PASSWORD", True, "Iceberg REST catalog's connection to Postgres"),
    ("MSSQL_SA_PASSWORD", True, "SQL Server sa account, source of the CDC stream"),
    ("MINIO_ROOT_USER", True, "Object store root identity"),
    ("MINIO_ROOT_PASSWORD", True, "Object store root credential"),
    ("AWS_ACCESS_KEY_ID", True, "What Trino and Flink present to MinIO"),
    ("AWS_SECRET_ACCESS_KEY", True, "Paired with the above"),
    ("NDA_API_KEY", True, "Caller key for the serving API"),
    ("ERASURE_PASSWORD", True, "The only principal permitted to DELETE, for GDPR erasure"),
]

# SQL Server rejects passwords without mixed case, a digit and a symbol, and the
# container exits with a message that does not mention the policy.
COMPLEX = {"MSSQL_SA_PASSWORD"}


def _value(name):
    token = secrets.token_urlsafe(24)
    return token + "aA1#" if name in COMPLEX else token


def path_for(runtime):
    return pathlib.Path(runtime) / "secrets.env"


def init(runtime, force=False):
    target = path_for(runtime)
    if target.exists() and not force:
        raise SystemExit(
            f"{target} already exists. Refusing to overwrite it - regenerating "
            f"secrets orphans every password already stored in Postgres, MinIO "
            f"and SQL Server.{os.linesep}  Pass --force only on a stack you are "
            f"rebuilding from empty volumes.")
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by `python -m delivery.secrets init`. Never commit this.",
             "# Regenerating it orphans the credentials already stored in the volumes.", ""]
    generated = 0
    for name, auto, why in REQUIRED:
        lines.append(f"# {why}")
        if auto:
            lines.append(f"{name}={_value(name)}")
            generated += 1
        else:
            lines.append(f"{name}=")
        lines.append("")
    target.write_text(os.linesep.join(lines), encoding="utf-8")
    # Readable only by the owner. The file holds every credential in the stack.
    try:
        os.chmod(target, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass
    print(f"Wrote {target} with {generated} generated secrets")
    blank = [n for n, auto, _ in REQUIRED if not auto]
    if blank:
        print("  Fill in by hand before deploying: " + ", ".join(blank))
    return target


def check(runtime):
    """Report what is missing without printing any value."""
    target = path_for(runtime)
    if not target.exists():
        print(f"  [FAIL] {target} does not exist")
        print("         python -m delivery.secrets init " + str(runtime))
        return 1
    present = {}
    for line in target.read_text(encoding="utf-8").splitlines():
        if line.strip() and not line.startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            present[key.strip()] = value.strip()
    missing = [n for n, _, _ in REQUIRED if not present.get(n)]
    weak = [n for n, _, _ in REQUIRED if 0 < len(present.get(n, "")) < 16]
    for name, _, why in REQUIRED:
        state = "missing" if name in missing else ("too short" if name in weak else "set")
        print(f"  [{'FAIL' if state != 'set' else 'ok'}] {name:26} {state:10} {why}")
    print()
    if missing or weak:
        print(f"{len(missing) + len(weak)} secret(s) need attention in {target}")
        return 1
    print(f"All {len(REQUIRED)} secrets present in {target}")
    return 0


def main():
    parser = argparse.ArgumentParser(description="The stack's secrets.env")
    parser.add_argument("action", choices=["init", "check"])
    parser.add_argument("runtime", nargs="?", default=os.environ.get("NDA_RUNTIME", "/var/lib/nda"))
    parser.add_argument("--force", action="store_true",
                        help="Overwrite an existing secrets.env. Only on empty volumes.")
    args = parser.parse_args()
    if args.action == "init":
        init(args.runtime, args.force)
        return 0
    return check(args.runtime)


if __name__ == "__main__":
    raise SystemExit(main())
